blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/ashishyd/npm-package-tester/discussions
    about: Ask questions and discuss ideas with the community
  - name: ğŸ“– Documentation
    url: https://github.com/ashishyd/npm-package-tester#readme
    about: Read the documentation
  - name: ğŸ¦ Twitter
    url: https://twitter.com/ashishyd
    about: Follow for updates and news
